
# Generated by CodiumAI

from tkinter import Entry, messagebox
from login import login
import pytest

class TestLogin:

    # User enters correct username and password
    def test_correct_username_and_password(self):
        usernameEntry = Entry()
        passwordEntry = Entry()
        usernameEntry.insert(0, 'Hicham')
        passwordEntry.insert(0, '1234')
        login()
        assert messagebox.showinfo.called_with('Success', 'Welcome')

    # User enters incorrect username and password
    def test_incorrect_username_and_password(self):
        usernameEntry = Entry()
        passwordEntry = Entry()
        usernameEntry.insert(0, 'John')
        passwordEntry.insert(0, '5678')
        login()
        assert messagebox.showerror.called_with('Error', 'Please enter correct credentials')

    # User leaves username field empty
    def test_empty_username_field(self):
        usernameEntry = Entry()
        passwordEntry = Entry()
        passwordEntry.insert(0, '1234')
        login()
        assert messagebox.showerror.called_with('Error', 'Fields cannot be empty')

    # Username contains special characters
    def test_username_with_special_characters(self):
        usernameEntry = Entry()
        passwordEntry = Entry()
        usernameEntry.insert(0, 'Hicham@')
        passwordEntry.insert(0, '1234')
        login()
        assert messagebox.showerror.called_with('Error', 'Please enter correct credentials')

    # Password contains special characters
    def test_password_with_special_characters(self):
        usernameEntry = Entry()
        passwordEntry = Entry()
        usernameEntry.insert(0, 'Hicham')
        passwordEntry.insert(0, '1234@')
        login()
        assert messagebox.showerror.called_with('Error', 'Please enter correct credentials')

    # Username and password contain maximum allowed characters
    def test_maximum_allowed_characters(self):
        usernameEntry = Entry()
        passwordEntry = Entry()
        usernameEntry.insert(0, 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ')
        passwordEntry.insert(0, '1234567890!@#$%^&*()_+{}|:"<>?')
        login()
        assert messagebox.showerror.called_with('Error', 'Please enter correct credentials')